import Image from "next/image"
import Link from "next/link"
import { ArrowUpRight } from "lucide-react"
import type { GlobalContent, ServicesPage } from "@/content/schema"
import { ProcessCardStack } from "./process-card-stack"
const bands={cobalt:"bg-primary text-primary-foreground",lavender:"bg-lavender text-foreground",terracotta:"bg-accent text-accent-foreground",mustard:"bg-mustard text-foreground"}
export function ServicesHero({content,steps}:{content:ServicesPage["hero"],steps:GlobalContent["processSteps"]}){return <section className="mx-auto grid max-w-7xl gap-16 px-5 py-20 md:grid-cols-2 md:px-6 md:py-28"><div><p className="eyebrow text-muted-foreground">{content.eyebrow}</p><h1 className="mt-6 text-balance text-5xl font-medium leading-[1.02] tracking-tight md:text-7xl">{content.headlineDark}<span className="block text-accent">{content.headlineAccent}</span></h1><p className="mt-6 max-w-xl text-base leading-relaxed text-muted-foreground md:text-lg">{content.body}</p><div className="mt-8 flex flex-wrap items-center gap-6"><Link href={content.primaryCta.href} className="rounded-full bg-ink px-7 py-4 text-sm text-primary-foreground">{content.primaryCta.label}</Link><Link href={content.secondaryCta.href} className="flex items-center gap-2 border-b border-foreground pb-1 text-sm">{content.secondaryCta.label}<ArrowUpRight size={15}/></Link></div></div><ProcessCardStack steps={steps}/></section>}
export function Capabilities({intro,steps,strips}:{intro:ServicesPage["capabilitiesIntro"],steps:GlobalContent["processSteps"],strips:ServicesPage["photoStrips"]}){return <section id="capabilities"><div className="mx-auto max-w-7xl px-5 py-20 md:px-6 md:py-28"><p className="eyebrow">{intro.eyebrow}</p><h2 className="mt-5 max-w-4xl text-balance text-5xl tracking-tight md:text-7xl">{intro.headingPlain} <span className="text-accent">{intro.headingAccent}</span></h2></div>{steps.map((step,index)=>{const strip=strips.find(s=>s.afterStepId===step.id);return <div key={step.id}><article className={`px-5 py-20 md:px-6 md:py-28 ${bands[step.bandColor]}`}><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><span className="text-sm">{step.number}</span><h3 className="mt-8 text-balance text-4xl font-semibold tracking-tight md:text-6xl">{step.heading}</h3><p className="mt-6 max-w-xl text-lg leading-relaxed opacity-80">{step.longDescription}</p></div><div className="flex flex-col gap-10 lg:pt-12"><List title="What We Do" items={step.whatWeDo}/><List title="Client Outcomes" items={step.clientOutcomes}/></div></div></article>{strip&&index<3?<div className="relative aspect-[4/3] w-full md:aspect-[32/9]"><Image src={strip.src.replace('.jpg','.png')} alt={strip.alt} fill sizes="100vw" className="object-cover"/></div>:null}</div>})}</section>}
function List({title,items}:{title:string,items:string[]}){return <div><h4 className="text-sm font-bold uppercase tracking-widest">{title}</h4><ul className="mt-4 flex flex-col gap-2">{items.map(i=><li key={i} className="flex gap-3 before:content-['—']">{i}</li>)}</ul></div>}
export function SectorGrid({content}:{content:ServicesPage["sectorGrid"]}){return <section className="mx-auto max-w-7xl px-5 py-20 md:px-6 md:py-28"><h2 className="max-w-4xl text-5xl tracking-tight md:text-7xl">{content.heading} <span className="text-accent">{content.headingAccent}</span></h2><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">{content.subheading}</p><div className="mt-16 border-t border-border">{content.sectors.map(row=><div key={row.sector} className="grid gap-6 border-b border-border py-8 md:grid-cols-[18rem_1fr]"><h3 className="flex items-start gap-3 text-lg font-semibold before:mt-2 before:size-2 before:shrink-0 before:rounded-full before:bg-accent">{row.sector}</h3><div className="flex flex-wrap gap-x-8 gap-y-4">{row.clients.map(c=><span key={c} className="text-lg text-muted-foreground">{c}</span>)}</div></div>)}</div><Link href={content.cta.href} className="mt-12 inline-flex items-center gap-2 border-b border-foreground pb-1">{content.cta.label}<ArrowUpRight size={16}/></Link></section>}
